# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=126, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('image', filebrowser.fields.FileBrowseField(max_length=500, verbose_name='Изображение')),
                ('url', models.URLField(blank=True, help_text='<br><i>\n<code>http://google.com</code>\nЛюбая ссылка на веб страницу или веб-ресурс.</i>\n', null=True, verbose_name='Полный путь к веб-странице')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1000, help_text='<br><i>\nЛучше использовать за единицу сортировки 1000 или 100.. \nТак проще будет разобраться, если элементы имеют большую вложенность.<br>\nИли придумайте свою систему сортировки : )\n<br>ПРИМЕР - 1000:__________________ПРИМЕР - 2000:\n<br>.... Пример - 1100__________________.... Пример - 2200\n<br>........... пример - 1110__________________........ пример - 2220\n<br>............... пример - 1111__________________............... пример - 2222</i>\n', null=True, verbose_name='Сортировка')),
            ],
            options={
                'ordering': ('sort',),
                'verbose_name': 'слайды',
                'verbose_name_plural': 'слайдер',
            },
        ),
    ]
