# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 10:15
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhome',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=500, null=True, verbose_name='Изображение'),
        ),
    ]
