# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhome',
            name='title',
            field=models.CharField(blank=True, max_length=126, null=True, verbose_name='Название'),
        ),
    ]
