# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0004_tag'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(blank=True, to='site_info.Tag', verbose_name='Тэги'),
        ),
    ]
