# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ('product', '-is_main', 'name'), 'verbose_name': 'Вариант продукта', 'verbose_name_plural': 'Варианты продукта'},
        ),
    ]
