# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 20:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0001_initial'),
        ('site_info', '0001_initial'),
        ('catalog', '0001_initial'),
        ('gallery', '0001_initial'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Нижний футер', max_length=125, unique=True, verbose_name='Заголовок')),
                ('is_show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('blogs', models.ManyToManyField(blank=True, to='blog.Blog', verbose_name='Блоги')),
                ('catalog', models.ManyToManyField(blank=True, to='catalog.Catalog', verbose_name='Каталоги')),
                ('galleries', models.ManyToManyField(blank=True, to='gallery.Gallery', verbose_name='Галереи')),
                ('list_link', models.ManyToManyField(blank=True, to='site_info.ListLink', verbose_name='Быстрые ссылки')),
                ('page', models.ManyToManyField(blank=True, to='page.Page', verbose_name='Страницы')),
                ('text_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_info.TextInfo', verbose_name='Текстовое оформление')),
            ],
            options={
                'verbose_name': 'футер',
                'verbose_name_plural': 'настрока футера',
            },
        ),
        migrations.CreateModel(
            name='SettingsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Основной шаблон', help_text='\nШаблонов может быть несколько. Например, для новогодних праздников можно создать<br>\n*футер<br>*главную страницу<br>*Подключить другие скрипты, ссылки и т.д.<br>\nОдним словом, с помощью настроек можно создать разные варианты отображения информации : )\n', max_length=125, unique=True, verbose_name='Заголовок')),
                ('is_included', models.BooleanField(default=False, help_text='Включеной может быть только одина главная страница', verbose_name='Включена')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email проекта')),
                ('phone', models.CharField(blank=True, help_text='Например: ``8(800)-000-00-00``<br>Основной, общий номер телефона. Виден всем.', max_length=30, null=True, unique=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, default='Адрес', max_length=255, null=True, verbose_name='Адрес')),
                ('logo', filebrowser.fields.FileBrowseField(blank=True, help_text='Основной логотип сайта.', max_length=500, null=True, verbose_name='Логотип')),
                ('robots_txt', models.TextField(blank=True, default='User-agent: Yandex\r\nDisallow: /admin', help_text='User-agent: Yandex\r\nDisallow: /admin', null=True, verbose_name='Содержимое robots.txt')),
                ('terms_of_use', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Пользовотельское соглашение')),
                ('scripts', models.TextField(blank=True, help_text='\nПример: "Подключение CSS фрэймворка - Bootstrap 4.0"<br>\n--------------------------------------------------------<br> \n< script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script><br>\n< script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script><br>\n< script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>\n', null=True, verbose_name='Блок скриптов')),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings_template.Footer', verbose_name='футер')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Home', verbose_name='Главная страница')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Сайт/Домен')),
            ],
            options={
                'verbose_name': 'настройку шаблона',
                'verbose_name_plural': 'основные настройка шаблона',
            },
        ),
    ]
