# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingstemplate',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: Yandex\r\nDisallow: /admin\r\nDisallow: /dev_init', help_text='User-agent: Yandex\r\nDisallow: /admin\r\nDisallow: /dev_init', null=True, verbose_name='Содержимое robots.txt'),
        ),
    ]
