# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'футер', 'verbose_name_plural': 'настрока футера'},
        ),
        migrations.RemoveField(
            model_name='footer',
            name='sort',
        ),
        migrations.AlterField(
            model_name='settingstemplate',
            name='address',
            field=models.CharField(blank=True, default='Адрес', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='settingstemplate',
            name='phone',
            field=models.CharField(blank=True, default='*Номер телефона', max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
