# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_template', '0002_auto_20180404_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='list_link',
            field=models.ManyToManyField(blank=True, to='site_info.ListLink', verbose_name='Быстрые ссылки'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='text_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_info.TextInfo', verbose_name='Текстовое оформление'),
        ),
    ]
