# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_template', '0002_auto_20180422_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingstemplate',
            name='robots_txt',
            field=models.TextField(blank=True, default='\nUser-agent: Yandex\r\n\nDisallow: /admin\r\n\nDisallow: /dev__init\r\n\nSitemap: http://dervek.ru/sitemap.xml\r\n\nHost: dervek.ru\r\n\n\nUser-agent: *\r\n\nDisallow: /admin\r\n\nDisallow: /dev__init\r\n\nSitemap: http://dervek.ru/sitemap.xml\r\n\nHost: dervek.ru\r\n\n', help_text='\nUser-agent: Yandex\r\n\nDisallow: /admin\r\n\nDisallow: /dev__init\r\n\nSitemap: http://dervek.ru/sitemap.xml\r\n\nHost: dervek.ru\r\n\n\nUser-agent: *\r\n\nDisallow: /admin\r\n\nDisallow: /dev__init\r\n\nSitemap: http://dervek.ru/sitemap.xml\r\n\nHost: dervek.ru\r\n\n', null=True, verbose_name='Содержимое robots.txt'),
        ),
    ]
