# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_template', '0003_auto_20180404_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingstemplate',
            name='phone',
            field=models.CharField(blank=True, help_text='Например: ``8(800)-000-00-00``<br>Основной, общий номер телефона. Виден всем.', max_length=30, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
