# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_template', '0004_auto_20180410_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingstemplate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email проекта'),
        ),
    ]
