# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0004_tag'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, to='site_info.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='pagecomment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
