# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 20:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=125, verbose_name='Заголовок')),
                ('url', models.URLField(blank=True, db_index=True, max_length=255, null=True, verbose_name='URL страницы')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
                ('is_show', models.BooleanField(default=True, verbose_name='Показать/Скрыть')),
                ('type_link', models.CharField(choices=[('L', 'ссылки'), ('T', 'тэги')], default=('L', 'ссылки'), help_text='\nСоздает CSS классы, в зависимости от выбраного типа. ``L_link``-ссылка или ``T_link``-тэг.<br>\nЕсли выбран тип ``ссылка`` - страница будет открываться в новой вкладке. <br>\nЕсли ``T_link`` страница будет открываться в новой вкладке!<br>\n', max_length=1, verbose_name='Вид ссылки')),
            ],
            options={
                'verbose_name': 'быстрая ссылка',
                'verbose_name_plural': 'быстрые ссылки',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название фото')),
                ('image_is_main', models.BooleanField(default=False, help_text='Главным может быть только одно фото', verbose_name='Главное')),
                ('image_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание фото')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=512, null=True, verbose_name='Иконка')),
                ('html_link', models.CharField(blank=True, help_text='\nПримеры некоторых иконок соц.сетей:<br> \n`````````````````````````````````````````````````<br>\n``< i class="fa fa-facebook"> < /i>`` - facebook<br>\n``< i class="fa fa-twitter">< /i>`` - twitter<br>\n``< i class="fa fa-instagram">< /i>`` - instagram<br>\n``< i class="fa fa-google-plus">< /i>`` - google-plus<br>\n``< i class="fa fa-envelope">`` - envelope<br>\n', max_length=512, null=True, unique=True, verbose_name='НТМЛ-ссылка')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL страницы')),
            ],
            options={
                'verbose_name': 'социальная сеть',
                'verbose_name_plural': 'социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='TextInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, unique=True, verbose_name='Заголовок')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст/HTML')),
            ],
            options={
                'verbose_name': 'текстовая информация',
                'verbose_name_plural': 'текстовые информации',
            },
        ),
    ]
