# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listlink',
            name='type_link',
            field=models.CharField(choices=[('L', 'ссылки'), ('T', 'тэги')], default=('L', 'ссылки'), help_text='добавляет CSS класс..', max_length=1, verbose_name='Вид ссылки'),
        ),
    ]
