# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0002_auto_20180404_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listlink',
            name='type_link',
            field=models.CharField(choices=[('L', 'ссылки'), ('T', 'тэги')], default=('L', 'ссылки'), help_text='\nСоздает CSS классы, в зависимости от выбраного типа. ``L_link``-ссылка или ``T_link``-тэг.<br>\nЕсли выбран тип ``ссылка`` - страница будет открываться в новой вкладке. <br>\nЕсли ``T_link`` страница будет открываться в новой вкладке!<br>\n', max_length=1, verbose_name='Вид ссылки'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='html_link',
            field=models.CharField(blank=True, help_text='\nПримеры некоторых иконок соц.сетей:<br> \n`````````````````````````````````````````````````<br>\n``< i class="fa fa-facebook"> < /i>`` - facebook<br>\n``< i class="fa fa-twitter">< /i>`` - twitter<br>\n``< i class="fa fa-instagram">< /i>`` - instagram<br>\n``< i class="fa fa-google-plus">< /i>`` - google-plus<br>\n``< i class="fa fa-envelope">`` - envelope<br>\n', max_length=512, null=True, unique=True, verbose_name='НТМЛ-ссылка'),
        ),
    ]
