# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncludeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_show', models.BooleanField(default=True, verbose_name='Отображать')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=500, null=True, verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('html_code', models.CharField(blank=True, help_text='HTML разметка с CSS', max_length=255, null=True, verbose_name='HTML-код')),
                ('code', models.CharField(choices=[('advantages', 'Наши преимущества')], default='advantages', help_text="<i>\nПринцип работы:<br> \n<b>advantages</b> - кодовое название Включаемой облости.<br>\nI.  Проинициализировать кодовое слово в ``CHOICES``(<b>advantages</b>).<br>\nII. Создать HTML шаблон с кодовым словом ~/include_area/templates/<b>advantages</b>.html<br>\nIII. Чтобы отображать его в любом месте сайта - нужно в HTML страницы/шаблона прописать тэг:<br>\n<code><small>{% get_include_area request code='<b>advantages</b>' %}</small></code>\n</i>", max_length=20, verbose_name='Код')),
                ('sort', models.PositiveSmallIntegerField(default=1000, help_text='<br><i>\nЛучше использовать за единицу сортировки 1000 или 100.. \nТак проще будет разобраться, если элементы имеют большую вложенность.<br>\nИли придумайте свою систему сортировки : )\n<br>ПРИМЕР - 1000:__________________ПРИМЕР - 2000:\n<br>.... Пример - 1100__________________.... Пример - 2200\n<br>........... пример - 1110__________________........ пример - 2220\n<br>............... пример - 1111__________________............... пример - 2222</i>\n', verbose_name='Сортировка')),
            ],
            options={
                'ordering': ('sort', 'code'),
                'verbose_name_plural': 'Включаемые области',
                'verbose_name': 'Включаемую область',
            },
        ),
        migrations.AlterUniqueTogether(
            name='includearea',
            unique_together=set([('title', 'code')]),
        ),
    ]
