# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 19:11
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обнавлен')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text=' Автоматический расчет при сохранении.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая стоимость')),
                ('ttn', models.CharField(blank=True, max_length=128, null=True, verbose_name='Товарно-транспортная накладная')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'заказы',
                'verbose_name': 'заказ',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Заказ')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductItem', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name_plural': 'пункты заказа',
                'verbose_name': 'пункт заказа',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Статусы заказов',
                'verbose_name': 'Статус заказа',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обнавлен')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общая стоимость')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Заказ')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Status', verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name_plural': 'История',
                'verbose_name': 'Историю',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Status', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together=set([('order', 'status', 'total_cost')]),
        ),
    ]
